In [2]:
import numpy as np

In [8]:
array_dual=np.random.random((2,3,4))
array_dual

array([[[0.14810139, 0.51114272, 0.37874161, 0.89008056],
        [0.56381126, 0.52808562, 0.55600616, 0.35491789],
        [0.26745012, 0.84823524, 0.19944886, 0.72106536]],

       [[0.97922102, 0.34941501, 0.98076006, 0.59880106],
        [0.25916253, 0.39697499, 0.87224964, 0.42185105],
        [0.65097984, 0.66844849, 0.5662334 , 0.22521923]]])

In [27]:
array_single=np.random.random(50)
array_single

array([0.00161142, 0.02726877, 0.10450682, 0.04659453, 0.609696  ,
       0.43384955, 0.01820347, 0.62610273, 0.37397087, 0.71541475,
       0.6778145 , 0.70980311, 0.78384491, 0.24580626, 0.55210049,
       0.04194697, 0.90320107, 0.98559797, 0.15098756, 0.33689676,
       0.20744889, 0.60808776, 0.20741141, 0.72919855, 0.11079161,
       0.64103792, 0.36536512, 0.48383455, 0.28437881, 0.26302632,
       0.65454648, 0.9102698 , 0.6796778 , 0.18960082, 0.17412137,
       0.9894539 , 0.37948341, 0.36013368, 0.41287758, 0.53327514,
       0.73167988, 0.66452227, 0.60439552, 0.65469505, 0.05519213,
       0.59514517, 0.96912396, 0.58220113, 0.87597196, 0.96432391])

In [36]:
array_single.ndim

1

# EXERCICI 1

In [58]:
def resumir (matriu):
    if (matriu.ndim > 1):
        print("ERROR FATAL: la matriu entrada conté més d'una dimensió")
    else:
        #ALERTA, el mètode nomes funciona perquè matriu és unidimensional. ELSE matriu(axis=1....n)
        out=[]
        mean = matriu.mean()
        sd = matriu.std()
        max_val = matriu.max()
        min_val =  matriu.min()
        pc = np.percentile(matriu, [25, 75] )
        out.append((mean, sd, max_val, min_val, pc[0], pc[1]))
        resum=np.array(out, dtype=None)
        np.set_printoptions(suppress=True)
        print("    MEAN       StDEV          MAX         MIN        25%         75%")
        print(resum)
    return (resum)

In [59]:
resumir(array_single)

    MEAN       StDEV          MAX         MIN        25%         75%
[[0.48452981 0.29230875 0.9894539  0.00161142 0.21703823 0.67921198]]


array([[0.48452981, 0.29230875, 0.9894539 , 0.00161142, 0.21703823,
        0.67921198]])

# EXERCICI 2

In [65]:
def rndmtrx (ndim):
    m=100*np.random.random((ndim,ndim))
    return(m)

In [67]:
rndmtrx(3)

array([[66.72099525, 91.48963036, 52.49120537],
       [20.94668924, 15.22118877, 68.52030733],
       [58.27880585, 96.62624048, 94.42227967]])

# EXERCICI 3

In [71]:
def summa (matrix):
    if (matrix.ndim==2):
        out=[]
        a=matrix.sum(axis=0) #vector suma per files
        b=matrix.sum(axis=1) #vector suma per columnes *notant que la presentacio és transposada en pantalla
        out.append((a, b))
        resultats=np.array(out, dtype=None)
    else:
        print("La matriu no té format bidimensional")
    return (resultats)

In [77]:
var=rndmtrx(3)
print(var)
summa(var)

[[ 4.14814345 20.01494365 78.16341002]
 [32.49152052 39.7691778  58.14480473]
 [23.17262311 96.43026558 26.46321237]]


array([[[ 59.81228708, 156.21438703, 162.77142713],
        [102.32649712, 130.40550305, 146.06610106]]])

# EXERCICI 4

In [85]:
def correlacio (matvar):   #es calcula escombrant la matriu per files i columnes amb Rij=(Cij/(arrel(Cii*Cjj)))
    c=np.corrcoef(matvar)  #dona una mesura de la independència de 2 variables sent 0 independents i +/-1 una dependència total
    return (c)             #no indica CAUSALITAT, només correlació

In [86]:
correlacio(var)

[[ 1.          0.99727665 -0.27520953]
 [ 0.99727665  1.         -0.20355648]
 [-0.27520953 -0.20355648  1.        ]]


array([[ 1.        ,  0.99727665, -0.27520953],
       [ 0.99727665,  1.        , -0.20355648],
       [-0.27520953, -0.20355648,  1.        ]])